apiVersion: batch/v1
kind: Cronjob
metadata:
  name: segment-backup-job
spec:
  schedule: "0 0 * * *"  
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:                  
    spec:
      template:
        serviceAccountName: segment-backup-sa
        metadata:
          labels:               
            parent: "segment-backup-job"
        spec:
          containers:
          - name: segment-backup-job
            image: quay.io/grpereir/segment-backup-job
            command: ["/bin/bash",  "/opt/app-root/src/script.sh"]
          restartPolicy: OnFailure 